[masters]
todo-master ansible_host=34.142.168.222 private_ip=10.0.0.3

[workers]
todo-worker-1 ansible_host=35.247.183.44 private_ip=10.0.0.5
todo-worker-2 ansible_host=34.87.68.87 private_ip=10.0.0.4
todo-worker-3 ansible_host=35.187.251.104 private_ip=10.0.0.2

[k8s_cluster:children]
masters
workers
