[masters]
todo-master ansible_host=YOUR_MASTER_PUBLIC_IP private_ip=YOUR_MASTER_PRIVATE_IP

[workers]
todo-worker-1 ansible_host=YOUR_WORKER_1_PUBLIC_IP private_ip=YOUR_WORKER_1_PRIVATE_IP
todo-worker-2 ansible_host=YOUR_WORKER_2_PUBLIC_IP private_ip=YOUR_WORKER_2_PRIVATE_IP
todo-worker-3 ansible_host=YOUR_WORKER_3_PUBLIC_IP private_ip=YOUR_WORKER_3_PRIVATE_IP

[k8s_cluster:children]
masters
workers
